spring:
  application:
    name: Classroom
  datasource:
    url: jdbc:mysql://localhost:3306/Classroom
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
