spring:
  application:
    name: Classroom
  datasource:
    url: ${DB_HOST}${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
# file:
#   upload-dir: src/main/resources/static/uploads
